services:
  web:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  api:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/chat
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
