version: '3.8'
services:
  web:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  api:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=development

networks:
  default:
    driver: bridge
